// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifcuasrrnlprfuwsncsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmY3Vhc3JybmxwcmZ1d3NuY3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzc3MjksImV4cCI6MjA2MTk1MzcyOX0.OqPA5MNHZfYUpnotDFbPpZ4mdD8M3DKXhl6Pb-xNJSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);